<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
        body {
            background-color:green;
            text-align:center;
        }
        .submited {
            text-align:center;
            margin:200px;
            background-color: white;
        }
            
            
    </style>
</head>
<body>
    <h1 class="submited">Your name was submited!!!</h1>
    <button type="autofocus">Back</button>
</body>
</html>